spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daily_tracking
    username: root
    password: jkbeauty1208
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true